# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef43d92838d89bee94f34be00df040c4c678745e0fb6c77ccd7e7d4eb8f036c924dc1a633b0041e8681750eca4db5f7f63dc1722646aa26f3b643442e66bf095

test:
  secret_key_base: 5a8a257466b2cec731155e20eb24828a623ea8d441be8256a51ab1190c715a56efe899e95bd16d9ebf4b67248b86d91d3737bc0c53b5f31397b1beffd44740eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
